const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const KEY='nova-agent-state-v3';
const state={memory:{observations:[],tasks:[],preferences:{},feedback:[]},history:[],plan:[],pending:null,mode:'inspect'};
const modes={inspect:'Tarkista sivu ja kuvaile sen tarkoitus.',plan:'Luo turvallinen monivaiheinen suunnitelma tätä tehtävää varten.',extract:'Poimi sivulta tuotteet, otsikot, linkit ja hinnat.',audit:'Arvioi sivun rakenne, käytettävyys ja saavutettavuus.'};
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)Object.assign(state,saved)}catch(e){log('Muistia ei voitu ladata')} }
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderMemory()}
function now(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function log(text){state.history.unshift(`${now()} · ${text}`);state.history=state.history.slice(0,30);$('#logList').innerHTML=state.history.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}
function escapeHtml(x){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setState(label,kind='ready'){$('#agentState').textContent=label;$('#agentState').className=`state ${kind}`}
function pageData(){const text=document.body.innerText||'';const els=q=>$$(`${q}`).map(x=>x.textContent.trim()).filter(Boolean);const prices=els('*').filter(x=>/€|\$|\d+\s*(€|\$|eur|usd)/i.test(x)).slice(0,12);return{title:document.title||'Untitled',url:location.href,h1:$('h1')?.textContent.trim()||'',headings:els('h1,h2,h3').slice(0,20),paragraphs:els('p').slice(0,20),links:$$('a[href]').map(a=>({label:a.textContent.trim(),href:a.href})).filter(x=>x.label).slice(0,20),buttons:els('button,.button,.cta,.chip').slice(0,20),prices,cards:els('article,.product-card,.feature-panel,.info-card').filter(x=>x.length>20).slice(0,15),text:text.slice(0,6000)}}
function remember(type,value){state.memory.observations.unshift({type,value:String(value).slice(0,500),page:location.href,at:new Date().toISOString()});state.memory.observations=state.memory.observations.slice(0,100);save()}
function renderMemory(){const m=state.memory;$('#memoryStats').textContent=`${m.observations.length} havaintoa · ${m.tasks.length} tehtävää`;$('#memoryPreview').textContent=m.observations.length?m.observations.slice(0,8).map(x=>`${x.type}: ${x.value}`).join('\n'):'Muisti on tyhjä.'}
function planFor(task){const p=pageData();return[{name:'Lue nykyinen sivu',tool:'readPage',risk:'low'},{name:'Poimi rakenteellinen data',tool:'extractData',risk:'low'},{name:'Tee yhteenveto ja arvio',tool:'summarize',risk:'low'},{name:'Raportoi seuraava turvallinen toimi',tool:'recommend',risk:'low'}].map((x,i)=>({...x,id:i+1,task,page:p.title,status:'pending'}))}
function renderPlan(){const list=$('#planList');$('#stepCount').textContent=`${state.plan.length} vaihetta`;list.innerHTML=state.plan.length?state.plan.map((x,i)=>`<li class="${x.status}">${escapeHtml(x.name)} <small>(${x.tool})</small></li>`).join(''):'<li>Ei aktiivista suunnitelmaa</li>'}
function showApproval(message,action){state.pending=action;$('#approvalText').textContent=message;$('#approval').classList.remove('hidden');setState('Odottaa vahvistusta','busy')}
function hideApproval(){state.pending=null;$('#approval').classList.add('hidden')}
function readPage(){const p=pageData();remember('havainto',`Sivu: ${p.title}; H1: ${p.h1}`);return`readPage()\nOtsikko: ${p.title}\nH1: ${p.h1||'ei löydy'}\nOtsikot: ${p.headings.join(' | ')||'ei löydy'}\nLinkkejä: ${p.links.length}\nToimintoja: ${p.buttons.join(', ')||'ei löydy'}`}
function extractData(){const p=pageData();const data={title:p.title,headings:p.headings,links:p.links,prices:p.prices,cards:p.cards};remember('poiminta',JSON.stringify(data));return`extractData()\n${JSON.stringify(data,null,2)}`}
function summarize(){const p=pageData();const result=`summarize()\nSivu “${p.title}” sisältää ${p.headings.length} otsikkoa, ${p.links.length} linkkiä ja ${p.cards.length} sisältökorttia.\nPääaihe: ${p.h1||p.headings[0]||'ei pääteltävissä'}.\nSeuraava turvallinen toimi: tarkista poimittu data ja pyydä agentilta tarkennettu tehtävä.`;remember('yhteenveto',result);return result}
function audit(){const p=pageData();return`audit()\nTitle: ${p.title?'OK':'PUUTTUU'}\nH1: ${p.h1?'OK':'PUUTTUU'}\nNavigointi: ${p.links.length?'OK':'PUUTTUU'}\nToimintokehotteet: ${p.buttons.length?'OK':'PUUTTUU'}\nHavaittu hinnasto: ${p.prices.length?'KYLLÄ':'EI'}\nSuositus: lisää semanttisia otsikoita, lomake-etiketit ja näppäimistöfokus.`}
function executeTool(tool){if(tool==='readPage')return readPage();if(tool==='extractData')return extractData();if(tool==='summarize')return summarize();if(tool==='audit')return audit();if(tool==='recommend')return' recommend()\nAgentti suosittelee tarkistamaan tuloksen ja hyväksymään mahdolliset lomake- tai navigointitoimet erikseen.';return`Tuntematon työkalu: ${tool}`}
function createPlan(){const task=$('#taskInput').value.trim()||modes[state.mode];state.plan=planFor(task);state.memory.tasks.unshift({task,page:location.href,created:new Date().toISOString(),steps:state.plan.map(x=>x.tool)});state.memory.tasks=state.memory.tasks.slice(0,30);save();renderPlan();$('#output').textContent=`Suunnitelma tehtävälle:\n${task}\n\n${state.plan.map(x=>`${x.id}. ${x.name}`).join('\n')}`;log('Suunnitelma luotu');setState('Suunnitelma valmis','done')}
async function executePlan(){if(!state.plan.length)createPlan();setState('Suorittaa','busy');let report=[];for(let i=0;i<state.plan.length;i++){const step=state.plan[i];step.status='active';renderPlan();log(`Vaihe ${i+1}: ${step.tool}`);await new Promise(r=>setTimeout(r,220));if(step.risk!=='low'){showApproval(`Agentti haluaa suorittaa: ${step.name}`,step);return}report.push(executeTool(step.tool));step.status='done';renderPlan()}$('#output').textContent=report.join('\n\n');remember('suoritus',`Suunnitelma valmis: ${state.plan.length} vaihetta`);save();setState('Valmis','done');log('Suunnitelma suoritettu')}
function runTask(){const task=$('#taskInput').value.trim();if(!task){$('#output').textContent='Kirjoita ensin tehtävä.';setState('Tehtävä puuttuu','error');return}state.memory.feedback.unshift({task,at:new Date().toISOString()});state.memory.feedback=state.memory.feedback.slice(0,50);state.memory.lastTask=task;save();createPlan();executePlan()}
function inspect(){const p=pageData();$('#output').textContent=readPage();log('Pikatarkistus');setState('Tarkistettu','done');remember('pikatarkistus',p.title)}
function exportMemory(){const blob=new Blob([JSON.stringify(state.memory,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='nova-agent-memory.json';a.click();URL.revokeObjectURL(a.href)}
function setup(){load();renderMemory();renderPlan();const p=pageData();$('#pageTitle').textContent=p.title;$('#pageUrl').textContent=p.url;log('Istunto aloitettu');$$('.nav-item').forEach(b=>b.onclick=()=>{ $$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;$('#taskInput').value=modes[state.mode]});$('#runTask').onclick=runTask;$('#planTask').onclick=createPlan;$('#executePlan').onclick=executePlan;$('#inspectTask').onclick=inspect;$('#copyOutput').onclick=()=>navigator.clipboard?.writeText($('#output').textContent);$('#clearMemory').onclick=()=>{if(confirm('Tyhjennetäänkö paikallinen muisti?')){state.memory={observations:[],tasks:[],preferences:{},feedback:[]};save();log('Muisti tyhjennetty')}};$('#exportMemory').onclick=exportMemory;$('#importMemory').onclick=()=>$('#memoryFile').click();$('#memoryFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{Object.assign(state.memory,JSON.parse(await file.text()));save();log('Muisti tuotu')}catch{log('Muistin tuonti epäonnistui')}};$('#approveAction').onclick=()=>{if(state.pending){const action=state.pending;hideApproval();action.status='done';renderPlan();$('#output').textContent='Toiminto hyväksytty. Tässä prototyypissä riskialttiit ulkoiset toimet pysäytetään edelleen ennen lähetystä.';log('Toiminto hyväksytty');setState('Valmis','done')}};$('#rejectAction').onclick=()=>{hideApproval();log('Toiminto hylätty');setState('Pysäytetty','error')};$('#taskInput').value=modes.inspect}
setup();
